/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * APIs
 * API Documents
 * OpenAPI spec version: 1.0.0
 */
import { fetchMutator } from '../mutators/fetch';
export interface PlatformAdminLoginDto {
  /** Admin username */
  username: string;
  /** Admin password */
  password: string;
}

/**
 * Database type
 */
export type CreateAppDtoDatabaseType = typeof CreateAppDtoDatabaseType[keyof typeof CreateAppDtoDatabaseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAppDtoDatabaseType = {
  postgres: 'postgres',
  mongodb: 'mongodb',
  mysql: 'mysql',
  mariadb: 'mariadb',
  sqlite: 'sqlite',
  mssql: 'mssql',
  oracle: 'oracle',
} as const;

/**
 * Additional metadata
 */
export type CreateAppDtoMetadata = { [key: string]: unknown };

export interface CreateAppDto {
  /** Unique app identifier */
  appId: string;
  /** App name */
  appName: string;
  /** Database type */
  databaseType: CreateAppDtoDatabaseType;
  /** Database host */
  databaseHost?: string;
  /** Database port */
  databasePort?: number;
  /** Database name */
  databaseName?: string;
  /** Database username */
  databaseUsername?: string;
  /** Database password */
  databasePassword?: string;
  /** Database URL (for MongoDB) */
  databaseUrl?: string;
  /** Enabled modules */
  enabledModules: string[];
  /** Additional metadata */
  metadata?: CreateAppDtoMetadata;
}

/**
 * Database type
 */
export type UpdateAppDtoDatabaseType = typeof UpdateAppDtoDatabaseType[keyof typeof UpdateAppDtoDatabaseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAppDtoDatabaseType = {
  postgres: 'postgres',
  mongodb: 'mongodb',
  mysql: 'mysql',
  mariadb: 'mariadb',
  sqlite: 'sqlite',
  mssql: 'mssql',
  oracle: 'oracle',
} as const;

/**
 * Additional metadata
 */
export type UpdateAppDtoMetadata = { [key: string]: unknown };

export interface UpdateAppDto {
  /** App name */
  appName?: string;
  /** Database type */
  databaseType?: UpdateAppDtoDatabaseType;
  /** Database host */
  databaseHost?: string;
  /** Database port */
  databasePort?: number;
  /** Database name */
  databaseName?: string;
  /** Database username */
  databaseUsername?: string;
  /** Database password */
  databasePassword?: string;
  /** Database URL (for MongoDB) */
  databaseUrl?: string;
  /** Enabled modules */
  enabledModules?: string[];
  /** Additional metadata */
  metadata?: UpdateAppDtoMetadata;
}

export interface AppEnvDto {
  /** App environment ID */
  id?: string;
  /** App ID */
  appId: string;
  /** JWT Auth Secret */
  jwsAuthSecret?: string;
  /** JWT Auth Expiry */
  jwsAuthExpiry?: string;
  /** JWT Unverified Auth Secret */
  jwsUnverifiedAuthSecret?: string;
  /** JWT Unverified Auth Expiry */
  jwsUnverifiedAuthExpiry?: string;
  /** JWT Admin Auth Secret */
  jwsAdminAuthSecret?: string;
  /** JWT Admin Auth Expiry */
  jwsAdminAuthExpiry?: string;
  /** Refresh Token Expiry */
  refreshTokenExpiry?: string;
  /** Super Admin Username */
  superAdminUsername?: string;
  /** Super Admin Password */
  superAdminPassword?: string;
  /** Google Client ID */
  googleClientId?: string;
  /** Telegram Bot Token */
  telegramBotToken?: string;
  /** Mailer Host */
  mailerHost?: string;
  /** Mailer Port */
  mailerPort?: number;
  /** Mailer Secure */
  mailerSecure?: boolean;
  /** Mailer Username */
  mailerUsername?: string;
  /** Mailer Password */
  mailerPassword?: string;
  /** Mailer Sender Email */
  mailerSenderEmail?: string;
  /** Mailer Sender Name */
  mailerSenderName?: string;
  /** FarazSms Base URL */
  farazSmsBaseUrl?: string;
  /** FarazSms Pattern */
  farazSmsPattern?: string;
  /** FarazSms API Key */
  farazSmsApiKey?: string;
  /** FarazSms From Number */
  farazSmsFromNumber?: string;
  /** Zarinpal Merchant ID */
  zarinpalMerchantId?: string;
  /** Zarinpal Callback URL */
  zarinpalCallbackUrl?: string;
  /** Environment creation datetime */
  createdAt?: string;
  /** Environment last update datetime */
  updatedAt?: string;
}

export interface SginupUserDto {
  /** User Phone Number */
  phoneNumber: string;
  /** User email */
  email: string;
}

export interface LoginResponseDto {
  /** Access token for calling other apis */
  accessToken: string;
  /** Refresh token for getting new access tokens */
  refreshToken?: string;
  /** Refresh token expiration date */
  refreshTokenExpiresAt?: string;
  /** Time when OTP can be resent */
  canResendAt?: string;
}

/**
 * Social platform
 */
export type SocialLoginDtoPlatform = typeof SocialLoginDtoPlatform[keyof typeof SocialLoginDtoPlatform];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialLoginDtoPlatform = {
  google: 'google',
  telegram: 'telegram',
} as const;

export interface SocialLoginDto {
  /** Social platform */
  platform: SocialLoginDtoPlatform;
  /** Social platform token */
  token: string;
}

export interface BasicAuthUserDto {
  /** User Phone Number */
  phoneNumber: string;
  /** User email */
  email: string;
  /** Password of the user */
  password: string;
}

/**
 * Otp code type to verify
 */
export type VerifyOtpDtoType = typeof VerifyOtpDtoType[keyof typeof VerifyOtpDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyOtpDtoType = {
  AUTH: 'AUTH',
  RESET_PASSWORD: 'RESET_PASSWORD',
} as const;

/**
 * Otp code method to verify
 */
export type VerifyOtpDtoMethod = typeof VerifyOtpDtoMethod[keyof typeof VerifyOtpDtoMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyOtpDtoMethod = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;

export interface VerifyOtpDto {
  /** Otp code to verify */
  otpCode: string;
  /** Otp code type to verify */
  type: VerifyOtpDtoType;
  /** Otp code method to verify */
  method: VerifyOtpDtoMethod;
}

/**
 * OTP code type to send
 */
export type SendOtpDtoType = typeof SendOtpDtoType[keyof typeof SendOtpDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendOtpDtoType = {
  AUTH: 'AUTH',
  RESET_PASSWORD: 'RESET_PASSWORD',
} as const;

/**
 * Method to send OTP (SMS or EMAIL)
 */
export type SendOtpDtoMethod = typeof SendOtpDtoMethod[keyof typeof SendOtpDtoMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendOtpDtoMethod = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;

export interface SendOtpDto {
  /** OTP code type to send */
  type: SendOtpDtoType;
  /** Method to send OTP (SMS or EMAIL) */
  method?: SendOtpDtoMethod;
}

export interface RefreshTokenDto {
  /** Refresh token to get new access token */
  refreshToken: string;
}

export interface SetPasswordDto {
  /** Password of the user */
  newPassword: string;
}

export interface AdminLoginDto {
  /** Access token for calling other apis */
  username: string;
  /** Password for calling other apis */
  password: string;
}

export interface AdminRefreshTokenDto {
  /** Refresh token to get new access token */
  refreshToken: string;
}

export interface UserReadDto {
  /** User id */
  id: string;
  /** User name */
  name?: string;
  /** User phone number */
  phoneNumber?: string;
  /** User phone number verified */
  phoneNumberVerified?: boolean;
  /** User email */
  email?: string;
  /** User email verified */
  emailVerified: boolean;
}

export interface UpdateProfileDto {
  /** User name */
  name?: string;
}

export interface UpdatePasswordDto {
  /** Current password of the user */
  currentPassword: string;
  /** New password of the user */
  newPassword: string;
}

export interface AdminReadV1DTO {
  /** Admin username */
  username: string;
  /** Admin first name */
  firstName?: string;
  /** Admin last name */
  lastName?: string;
  /** Admin role */
  role?: string;
}

export interface AdminCreateV1DTO {
  /** Admin username */
  username: string;
  /** Admin password */
  password?: string;
  /** Admin first name */
  firstName?: string;
  /** Admin last name */
  lastName?: string;
  /** Admin role */
  role?: string;
}

export interface AdminUpdateV1DTO {
  /** Admin id */
  id?: string;
  /** Admin password */
  password?: string;
  /** Admin first name */
  firstName?: string;
  /** Admin last name */
  lastName?: string;
  /** Admin role */
  role?: string;
}

export interface AdminDeleteV1DTO {
  /** Admin username */
  username?: string;
}

/**
 * Value type for this event
 */
export type CreateEventDtoValueType = typeof CreateEventDtoValueType[keyof typeof CreateEventDtoValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEventDtoValueType = {
  none: 'none',
  string: 'string',
  bool: 'bool',
  number: 'number',
} as const;

export interface CreateEventDto {
  /** Event name */
  name: string;
  /** Event unique identifier (e.g., "Menu:Shop", "Games:MiniGames:Enter") */
  event: string;
  /** Category ID (nullable) */
  categoryId?: string;
  /** Tag IDs array (nullable) */
  tagIds?: string[];
  /** Prize ID (nullable) */
  prizeId?: string;
  /** Value type for this event */
  valueType: CreateEventDtoValueType;
}

/**
 * Value type for this event
 */
export type EventResponseDtoValueType = typeof EventResponseDtoValueType[keyof typeof EventResponseDtoValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventResponseDtoValueType = {
  none: 'none',
  string: 'string',
  bool: 'bool',
  number: 'number',
} as const;

export interface EventResponseDto {
  /** Event id */
  id: string;
  /** Event name */
  name: string;
  /** Event unique identifier */
  event: string;
  /** Category ID */
  categoryId?: string;
  /** Tag IDs array */
  tagIds?: string[];
  /** Prize ID */
  prizeId?: string;
  /** Value type for this event */
  valueType: EventResponseDtoValueType;
  /** Event creation datetime */
  createdAt: string;
  /** Event last update datetime */
  updatedAt: string;
}

/**
 * Value type for this event
 */
export type UpdateEventDtoValueType = typeof UpdateEventDtoValueType[keyof typeof UpdateEventDtoValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateEventDtoValueType = {
  none: 'none',
  string: 'string',
  bool: 'bool',
  number: 'number',
} as const;

export interface UpdateEventDto {
  /** Event name */
  name?: string;
  /** Event unique identifier (e.g., "Menu:Shop", "Games:MiniGames:Enter") */
  event?: string;
  /** Category ID (nullable, for future Category entity) */
  categoryId?: string;
  /** Tag IDs array (nullable, for future Tag entity) */
  tagIds?: string[];
  /** Prize ID (nullable, for future Prize entity) */
  prizeId?: string;
  /** Value type for this event */
  valueType?: UpdateEventDtoValueType;
}

/**
 * Event value (validated against Event.valueType: none, string, bool, number)
 */
export type SendEventDtoValue = { [key: string]: unknown };

/**
 * Additional data from client (any JSON object)
 */
export type SendEventDtoData = { [key: string]: unknown };

export interface SendEventDto {
  /** Event unique identifier (e.g., "Menu:Shop", "Games:MiniGames:Enter") */
  event: string;
  /** Event value (validated against Event.valueType: none, string, bool, number) */
  value?: SendEventDtoValue;
  /** Additional data from client (any JSON object) */
  data?: SendEventDtoData;
}

export interface EventCountResponseDto {
  /** Event ID */
  eventId: string;
  /** Event unique identifier */
  eventName: string;
  /** Number of times the event occurred */
  count: number;
  /** Start date of the query range */
  startDate?: string;
  /** End date of the query range */
  endDate?: string;
}

/**
 * Event value
 */
export type UserEventResponseDtoValue = { [key: string]: unknown };

/**
 * Additional data
 */
export type UserEventResponseDtoData = { [key: string]: unknown };

export interface UserEventResponseDto {
  /** User event id */
  id: string;
  /** Event ID */
  eventId: string;
  /** Event unique identifier */
  eventName: string;
  /** User ID */
  userId: string;
  /** Event occurrence timestamp */
  time: string;
  /** Event value */
  value?: UserEventResponseDtoValue;
  /** Additional data */
  data?: UserEventResponseDtoData;
  /** User event creation datetime */
  createdAt: string;
  /** User event last update datetime */
  updatedAt: string;
}

export type LeaderboardRewardsItem = { [key: string]: unknown };

export interface Leaderboard {
  /** Unique identifier for the leaderboard */
  id: string;
  /** Parent ID of the leaderboard */
  parentId: string;
  /** Name of the leaderboard */
  name?: string;
  /** Whether the leaderboard is active */
  isActive: boolean;
  /** Whether the leaderboard need tickets */
  ticket: boolean;
  /** Life cycle of the leaderboard */
  lifeCycle: number;
  /** Life span of the leaderboard */
  lifeSpan: number;
  /** Start date of the tournament */
  startDate: string;
  /** End date of the tournament */
  endDate: string;
  /** Rewards array with rank, amount and currency */
  rewards: LeaderboardRewardsItem[];
  /** Whether the rewards are distributed */
  isRewardsDistributed: boolean;
  /** Creation timestamp */
  createdAt: string;
}

export interface UserLeaderboardDto {
  /** Leaderboard ID */
  leaderboardId: string;
  /** User ID */
  userId: string;
  /** User display name */
  name: string;
  /** Rank of the user in the leaderboard */
  rank: number;
  /** Score of the user */
  score: number;
}

export interface UserLeaderboardWithNeighborsDto {
  /** Leaderboard ID */
  leaderboardId: string;
  /** User ID */
  userId: string;
  /** User display name */
  displayName: string;
  /** Rank of the user in the leaderboard */
  rank: number;
  /** Score of the user */
  score: number;
  /** Neighboring users in the leaderboard (3 above and 3 below, if available) */
  neighbors: UserLeaderboardDto[];
}

export type CreateLeaderboardDtoRewardsItem = { [key: string]: unknown };

export interface CreateLeaderboardDto {
  /** Key ID of the leaderboard */
  key?: string;
  /** Name of the leaderboard */
  name?: string;
  /** Whether the leaderboard requires tickets */
  ticket?: boolean;
  /** Life span of the leaderboard in days */
  lifeSpan?: number;
  /** Life cycle of the leaderboard */
  lifeCycle?: number;
  /** Rewards array with rank, amount and currency */
  rewards: CreateLeaderboardDtoRewardsItem[];
}

export type UpdateLeaderboardDtoRewardsItem = { [key: string]: unknown };

export interface UpdateLeaderboardDto {
  /** Name of the leaderboard */
  name?: string;
  /** Whether the leaderboard requires tickets */
  ticket?: boolean;
  /** Whether the leaderboard is active */
  isActive?: boolean;
  /** Life span of the leaderboard in days */
  lifeSpan?: number;
  /** Life cycle of the leaderboard */
  lifeCycle?: number;
  /** Rewards array with rank, amount and currency */
  rewards: UpdateLeaderboardDtoRewardsItem[];
}

export type EventAdminControllerFindAllParams = {
/**
 * Page number (starting from 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 */
limit?: number;
/**
 * Search by event name or identifier
 */
search?: string;
/**
 * Filter by value type
 */
valueType?: EventAdminControllerFindAllValueType;
/**
 * Filter by category ID
 */
categoryId?: string;
};

export type EventAdminControllerFindAllValueType = typeof EventAdminControllerFindAllValueType[keyof typeof EventAdminControllerFindAllValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventAdminControllerFindAllValueType = {
  none: 'none',
  string: 'string',
  bool: 'bool',
  number: 'number',
} as const;

export type EventUserControllerGetEventCountParams = {
/**
 * Start date for filtering events (ISO 8601 format)
 */
startDate?: string;
/**
 * End date for filtering events (ISO 8601 format)
 */
endDate?: string;
/**
 * Maximum number of results to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * Number of results to skip (for pagination)
 * @minimum 0
 */
offset?: number;
};

export type EventUserControllerGetEventHistoryParams = {
/**
 * Start date for filtering events (ISO 8601 format)
 */
startDate?: string;
/**
 * End date for filtering events (ISO 8601 format)
 */
endDate?: string;
/**
 * Maximum number of results to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * Number of results to skip (for pagination)
 * @minimum 0
 */
offset?: number;
};

export type EventUserControllerFindAllParams = {
/**
 * Page number (starting from 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 */
limit?: number;
/**
 * Search by event name or identifier
 */
search?: string;
/**
 * Filter by value type
 */
valueType?: EventUserControllerFindAllValueType;
/**
 * Filter by category ID
 */
categoryId?: string;
};

export type EventUserControllerFindAllValueType = typeof EventUserControllerFindAllValueType[keyof typeof EventUserControllerFindAllValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventUserControllerFindAllValueType = {
  none: 'none',
  string: 'string',
  bool: 'bool',
  number: 'number',
} as const;

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type HealthControllerCheck200Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type HealthControllerCheck200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type HealthControllerCheck503Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};

export type LeaderboardControllerGetTopScoresParams = {
/**
 * Page number
 */
page?: number;
/**
 * Limit number of records per page
 */
limit?: number;
};

/**
 * @summary Platform admin login
 */
export type platformAdminAuthControllerLoginResponse200 = {
  data: void
  status: 200
}

export type platformAdminAuthControllerLoginResponse401 = {
  data: void
  status: 401
}
    
export type platformAdminAuthControllerLoginResponseSuccess = (platformAdminAuthControllerLoginResponse200) & {
  headers: Headers;
};
export type platformAdminAuthControllerLoginResponseError = (platformAdminAuthControllerLoginResponse401) & {
  headers: Headers;
};

export type platformAdminAuthControllerLoginResponse = (platformAdminAuthControllerLoginResponseSuccess | platformAdminAuthControllerLoginResponseError)

export const getPlatformAdminAuthControllerLoginUrl = () => {


  

  return `/api/v1/platform/auth/login`
}

export const platformAdminAuthControllerLogin = async (platformAdminLoginDto: PlatformAdminLoginDto, options?: RequestInit): Promise<platformAdminAuthControllerLoginResponse> => {
  
  return fetchMutator<platformAdminAuthControllerLoginResponse>(getPlatformAdminAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      platformAdminLoginDto,)
  }
);}



/**
 * @summary Create a new app
 */
export type appManagementControllerCreateAppResponse201 = {
  data: void
  status: 201
}

export type appManagementControllerCreateAppResponse409 = {
  data: void
  status: 409
}
    
export type appManagementControllerCreateAppResponseSuccess = (appManagementControllerCreateAppResponse201) & {
  headers: Headers;
};
export type appManagementControllerCreateAppResponseError = (appManagementControllerCreateAppResponse409) & {
  headers: Headers;
};

export type appManagementControllerCreateAppResponse = (appManagementControllerCreateAppResponseSuccess | appManagementControllerCreateAppResponseError)

export const getAppManagementControllerCreateAppUrl = () => {


  

  return `/api/v1/platform/apps`
}

export const appManagementControllerCreateApp = async (createAppDto: CreateAppDto, options?: RequestInit): Promise<appManagementControllerCreateAppResponse> => {
  
  return fetchMutator<appManagementControllerCreateAppResponse>(getAppManagementControllerCreateAppUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAppDto,)
  }
);}



/**
 * @summary List all apps
 */
export type appManagementControllerListAppsResponse200 = {
  data: void
  status: 200
}
    
export type appManagementControllerListAppsResponseSuccess = (appManagementControllerListAppsResponse200) & {
  headers: Headers;
};
;

export type appManagementControllerListAppsResponse = (appManagementControllerListAppsResponseSuccess)

export const getAppManagementControllerListAppsUrl = () => {


  

  return `/api/v1/platform/apps`
}

export const appManagementControllerListApps = async ( options?: RequestInit): Promise<appManagementControllerListAppsResponse> => {
  
  return fetchMutator<appManagementControllerListAppsResponse>(getAppManagementControllerListAppsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get app details
 */
export type appManagementControllerGetAppResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerGetAppResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerGetAppResponseSuccess = (appManagementControllerGetAppResponse200) & {
  headers: Headers;
};
export type appManagementControllerGetAppResponseError = (appManagementControllerGetAppResponse404) & {
  headers: Headers;
};

export type appManagementControllerGetAppResponse = (appManagementControllerGetAppResponseSuccess | appManagementControllerGetAppResponseError)

export const getAppManagementControllerGetAppUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}`
}

export const appManagementControllerGetApp = async (appId: string, options?: RequestInit): Promise<appManagementControllerGetAppResponse> => {
  
  return fetchMutator<appManagementControllerGetAppResponse>(getAppManagementControllerGetAppUrl(appId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update app configuration
 */
export type appManagementControllerUpdateAppResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerUpdateAppResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerUpdateAppResponseSuccess = (appManagementControllerUpdateAppResponse200) & {
  headers: Headers;
};
export type appManagementControllerUpdateAppResponseError = (appManagementControllerUpdateAppResponse404) & {
  headers: Headers;
};

export type appManagementControllerUpdateAppResponse = (appManagementControllerUpdateAppResponseSuccess | appManagementControllerUpdateAppResponseError)

export const getAppManagementControllerUpdateAppUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}`
}

export const appManagementControllerUpdateApp = async (appId: string,
    updateAppDto: UpdateAppDto, options?: RequestInit): Promise<appManagementControllerUpdateAppResponse> => {
  
  return fetchMutator<appManagementControllerUpdateAppResponse>(getAppManagementControllerUpdateAppUrl(appId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAppDto,)
  }
);}



/**
 * @summary Deactivate an app
 */
export type appManagementControllerDeactivateAppResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerDeactivateAppResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerDeactivateAppResponseSuccess = (appManagementControllerDeactivateAppResponse200) & {
  headers: Headers;
};
export type appManagementControllerDeactivateAppResponseError = (appManagementControllerDeactivateAppResponse404) & {
  headers: Headers;
};

export type appManagementControllerDeactivateAppResponse = (appManagementControllerDeactivateAppResponseSuccess | appManagementControllerDeactivateAppResponseError)

export const getAppManagementControllerDeactivateAppUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}`
}

export const appManagementControllerDeactivateApp = async (appId: string, options?: RequestInit): Promise<appManagementControllerDeactivateAppResponse> => {
  
  return fetchMutator<appManagementControllerDeactivateAppResponse>(getAppManagementControllerDeactivateAppUrl(appId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get app environment variables
 */
export type appManagementControllerGetAppEnvResponse200 = {
  data: AppEnvDto
  status: 200
}

export type appManagementControllerGetAppEnvResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerGetAppEnvResponseSuccess = (appManagementControllerGetAppEnvResponse200) & {
  headers: Headers;
};
export type appManagementControllerGetAppEnvResponseError = (appManagementControllerGetAppEnvResponse404) & {
  headers: Headers;
};

export type appManagementControllerGetAppEnvResponse = (appManagementControllerGetAppEnvResponseSuccess | appManagementControllerGetAppEnvResponseError)

export const getAppManagementControllerGetAppEnvUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}/env`
}

export const appManagementControllerGetAppEnv = async (appId: string, options?: RequestInit): Promise<appManagementControllerGetAppEnvResponse> => {
  
  return fetchMutator<appManagementControllerGetAppEnvResponse>(getAppManagementControllerGetAppEnvUrl(appId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update app environment variables
 */
export type appManagementControllerUpdateAppEnvResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerUpdateAppEnvResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerUpdateAppEnvResponseSuccess = (appManagementControllerUpdateAppEnvResponse200) & {
  headers: Headers;
};
export type appManagementControllerUpdateAppEnvResponseError = (appManagementControllerUpdateAppEnvResponse404) & {
  headers: Headers;
};

export type appManagementControllerUpdateAppEnvResponse = (appManagementControllerUpdateAppEnvResponseSuccess | appManagementControllerUpdateAppEnvResponseError)

export const getAppManagementControllerUpdateAppEnvUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}/env`
}

export const appManagementControllerUpdateAppEnv = async (appId: string,
    appEnvDto: AppEnvDto, options?: RequestInit): Promise<appManagementControllerUpdateAppEnvResponse> => {
  
  return fetchMutator<appManagementControllerUpdateAppEnvResponse>(getAppManagementControllerUpdateAppEnvUrl(appId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      appEnvDto,)
  }
);}



/**
 * @summary Run migrations for an app
 */
export type appManagementControllerRunMigrationsResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerRunMigrationsResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerRunMigrationsResponseSuccess = (appManagementControllerRunMigrationsResponse200) & {
  headers: Headers;
};
export type appManagementControllerRunMigrationsResponseError = (appManagementControllerRunMigrationsResponse404) & {
  headers: Headers;
};

export type appManagementControllerRunMigrationsResponse = (appManagementControllerRunMigrationsResponseSuccess | appManagementControllerRunMigrationsResponseError)

export const getAppManagementControllerRunMigrationsUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}/migrate`
}

export const appManagementControllerRunMigrations = async (appId: string, options?: RequestInit): Promise<appManagementControllerRunMigrationsResponse> => {
  
  return fetchMutator<appManagementControllerRunMigrationsResponse>(getAppManagementControllerRunMigrationsUrl(appId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Revert last migration for an app
 */
export type appManagementControllerRevertMigrationResponse200 = {
  data: void
  status: 200
}

export type appManagementControllerRevertMigrationResponse404 = {
  data: void
  status: 404
}
    
export type appManagementControllerRevertMigrationResponseSuccess = (appManagementControllerRevertMigrationResponse200) & {
  headers: Headers;
};
export type appManagementControllerRevertMigrationResponseError = (appManagementControllerRevertMigrationResponse404) & {
  headers: Headers;
};

export type appManagementControllerRevertMigrationResponse = (appManagementControllerRevertMigrationResponseSuccess | appManagementControllerRevertMigrationResponseError)

export const getAppManagementControllerRevertMigrationUrl = (appId: string,) => {


  

  return `/api/v1/platform/apps/${appId}/migrate/revert`
}

export const appManagementControllerRevertMigration = async (appId: string, options?: RequestInit): Promise<appManagementControllerRevertMigrationResponse> => {
  
  return fetchMutator<appManagementControllerRevertMigrationResponse>(getAppManagementControllerRevertMigrationUrl(appId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Run migrations for all active apps
 */
export type appManagementControllerRunMigrationsForAllResponse200 = {
  data: void
  status: 200
}
    
export type appManagementControllerRunMigrationsForAllResponseSuccess = (appManagementControllerRunMigrationsForAllResponse200) & {
  headers: Headers;
};
;

export type appManagementControllerRunMigrationsForAllResponse = (appManagementControllerRunMigrationsForAllResponseSuccess)

export const getAppManagementControllerRunMigrationsForAllUrl = () => {


  

  return `/api/v1/platform/apps/migrate-all`
}

export const appManagementControllerRunMigrationsForAll = async ( options?: RequestInit): Promise<appManagementControllerRunMigrationsForAllResponse> => {
  
  return fetchMutator<appManagementControllerRunMigrationsForAllResponse>(getAppManagementControllerRunMigrationsForAllUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Run migrations for specific apps
 */
export type appManagementControllerRunMigrationsForBatchResponse200 = {
  data: void
  status: 200
}
    
export type appManagementControllerRunMigrationsForBatchResponseSuccess = (appManagementControllerRunMigrationsForBatchResponse200) & {
  headers: Headers;
};
;

export type appManagementControllerRunMigrationsForBatchResponse = (appManagementControllerRunMigrationsForBatchResponseSuccess)

export const getAppManagementControllerRunMigrationsForBatchUrl = () => {


  

  return `/api/v1/platform/apps/migrate-batch`
}

export const appManagementControllerRunMigrationsForBatch = async ( options?: RequestInit): Promise<appManagementControllerRunMigrationsForBatchResponse> => {
  
  return fetchMutator<appManagementControllerRunMigrationsForBatchResponse>(getAppManagementControllerRunMigrationsForBatchUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Login with phone number or email
 */
export type authControllerOtpAuthResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerOtpAuthResponseSuccess = (authControllerOtpAuthResponse200) & {
  headers: Headers;
};
;

export type authControllerOtpAuthResponse = (authControllerOtpAuthResponseSuccess)

export const getAuthControllerOtpAuthUrl = () => {


  

  return `/api/v1/auth/otp-login`
}

export const authControllerOtpAuth = async (sginupUserDto: SginupUserDto, options?: RequestInit): Promise<authControllerOtpAuthResponse> => {
  
  return fetchMutator<authControllerOtpAuthResponse>(getAuthControllerOtpAuthUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sginupUserDto,)
  }
);}



/**
 * @summary Login with social media
 */
export type authControllerSocialLoginResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerSocialLoginResponseSuccess = (authControllerSocialLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerSocialLoginResponse = (authControllerSocialLoginResponseSuccess)

export const getAuthControllerSocialLoginUrl = () => {


  

  return `/api/v1/auth/social-login`
}

export const authControllerSocialLogin = async (socialLoginDto: SocialLoginDto, options?: RequestInit): Promise<authControllerSocialLoginResponse> => {
  
  return fetchMutator<authControllerSocialLoginResponse>(getAuthControllerSocialLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      socialLoginDto,)
  }
);}



/**
 * @summary Signup with phone number or email
 */
export type authControllerBasicSignupResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerBasicSignupResponseSuccess = (authControllerBasicSignupResponse200) & {
  headers: Headers;
};
;

export type authControllerBasicSignupResponse = (authControllerBasicSignupResponseSuccess)

export const getAuthControllerBasicSignupUrl = () => {


  

  return `/api/v1/auth/basic-signup`
}

export const authControllerBasicSignup = async (basicAuthUserDto: BasicAuthUserDto, options?: RequestInit): Promise<authControllerBasicSignupResponse> => {
  
  return fetchMutator<authControllerBasicSignupResponse>(getAuthControllerBasicSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      basicAuthUserDto,)
  }
);}



/**
 * @summary Login with phone number or email
 */
export type authControllerBasicLoginResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerBasicLoginResponseSuccess = (authControllerBasicLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerBasicLoginResponse = (authControllerBasicLoginResponseSuccess)

export const getAuthControllerBasicLoginUrl = () => {


  

  return `/api/v1/auth/basic-login`
}

export const authControllerBasicLogin = async (basicAuthUserDto: BasicAuthUserDto, options?: RequestInit): Promise<authControllerBasicLoginResponse> => {
  
  return fetchMutator<authControllerBasicLoginResponse>(getAuthControllerBasicLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      basicAuthUserDto,)
  }
);}



/**
 * @summary logging out of account
 */
export type authControllerVerifyOtpResponse200 = {
  data: void
  status: 200
}
    
export type authControllerVerifyOtpResponseSuccess = (authControllerVerifyOtpResponse200) & {
  headers: Headers;
};
;

export type authControllerVerifyOtpResponse = (authControllerVerifyOtpResponseSuccess)

export const getAuthControllerVerifyOtpUrl = () => {


  

  return `/api/v1/auth/verify-otp`
}

export const authControllerVerifyOtp = async (verifyOtpDto: VerifyOtpDto, options?: RequestInit): Promise<authControllerVerifyOtpResponse> => {
  
  return fetchMutator<authControllerVerifyOtpResponse>(getAuthControllerVerifyOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyOtpDto,)
  }
);}



/**
 * @summary Resend OTP code
 */
export type authControllerResendOtpResponse200 = {
  data: void
  status: 200
}
    
export type authControllerResendOtpResponseSuccess = (authControllerResendOtpResponse200) & {
  headers: Headers;
};
;

export type authControllerResendOtpResponse = (authControllerResendOtpResponseSuccess)

export const getAuthControllerResendOtpUrl = () => {


  

  return `/api/v1/auth/resend-otp`
}

export const authControllerResendOtp = async (sendOtpDto: SendOtpDto, options?: RequestInit): Promise<authControllerResendOtpResponse> => {
  
  return fetchMutator<authControllerResendOtpResponse>(getAuthControllerResendOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendOtpDto,)
  }
);}



/**
 * @summary Refresh access token using refresh token
 */
export type authControllerRefreshTokenResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerRefreshTokenResponseSuccess = (authControllerRefreshTokenResponse200) & {
  headers: Headers;
};
;

export type authControllerRefreshTokenResponse = (authControllerRefreshTokenResponseSuccess)

export const getAuthControllerRefreshTokenUrl = () => {


  

  return `/api/v1/auth/refresh-token`
}

export const authControllerRefreshToken = async (refreshTokenDto: RefreshTokenDto, options?: RequestInit): Promise<authControllerRefreshTokenResponse> => {
  
  return fetchMutator<authControllerRefreshTokenResponse>(getAuthControllerRefreshTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenDto,)
  }
);}



/**
 * @summary logging out of account
 */
export type authControllerLogoutResponse200 = {
  data: void
  status: 200
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse200) & {
  headers: Headers;
};
;

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess)

export const getAuthControllerLogoutUrl = () => {


  

  return `/api/v1/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  return fetchMutator<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Reset password by email
 */
export type authControllerResetPasswordResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerResetPasswordResponseSuccess = (authControllerResetPasswordResponse200) & {
  headers: Headers;
};
;

export type authControllerResetPasswordResponse = (authControllerResetPasswordResponseSuccess)

export const getAuthControllerResetPasswordUrl = () => {


  

  return `/api/v1/auth/reset-password`
}

export const authControllerResetPassword = async (sginupUserDto: SginupUserDto, options?: RequestInit): Promise<authControllerResetPasswordResponse> => {
  
  return fetchMutator<authControllerResetPasswordResponse>(getAuthControllerResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sginupUserDto,)
  }
);}



/**
 * @summary Set password by email
 */
export type authControllerSetPasswordResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type authControllerSetPasswordResponseSuccess = (authControllerSetPasswordResponse200) & {
  headers: Headers;
};
;

export type authControllerSetPasswordResponse = (authControllerSetPasswordResponseSuccess)

export const getAuthControllerSetPasswordUrl = () => {


  

  return `/api/v1/auth/set-password`
}

export const authControllerSetPassword = async (setPasswordDto: SetPasswordDto, options?: RequestInit): Promise<authControllerSetPasswordResponse> => {
  
  return fetchMutator<authControllerSetPasswordResponse>(getAuthControllerSetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setPasswordDto,)
  }
);}



/**
 * @summary Admin login with username and password
 */
export type adminAuthControllerAuthenticateUserResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type adminAuthControllerAuthenticateUserResponseSuccess = (adminAuthControllerAuthenticateUserResponse200) & {
  headers: Headers;
};
;

export type adminAuthControllerAuthenticateUserResponse = (adminAuthControllerAuthenticateUserResponseSuccess)

export const getAdminAuthControllerAuthenticateUserUrl = () => {


  

  return `/api/v1/auth/admin/login`
}

export const adminAuthControllerAuthenticateUser = async (adminLoginDto: AdminLoginDto, options?: RequestInit): Promise<adminAuthControllerAuthenticateUserResponse> => {
  
  return fetchMutator<adminAuthControllerAuthenticateUserResponse>(getAdminAuthControllerAuthenticateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminLoginDto,)
  }
);}



/**
 * @summary Refresh admin access token using refresh token
 */
export type adminAuthControllerRefreshTokenResponse200 = {
  data: LoginResponseDto
  status: 200
}
    
export type adminAuthControllerRefreshTokenResponseSuccess = (adminAuthControllerRefreshTokenResponse200) & {
  headers: Headers;
};
;

export type adminAuthControllerRefreshTokenResponse = (adminAuthControllerRefreshTokenResponseSuccess)

export const getAdminAuthControllerRefreshTokenUrl = () => {


  

  return `/api/v1/auth/admin/refresh-token`
}

export const adminAuthControllerRefreshToken = async (adminRefreshTokenDto: AdminRefreshTokenDto, options?: RequestInit): Promise<adminAuthControllerRefreshTokenResponse> => {
  
  return fetchMutator<adminAuthControllerRefreshTokenResponse>(getAdminAuthControllerRefreshTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminRefreshTokenDto,)
  }
);}



/**
 * @summary Get the profile of user
 */
export type userControllerMeResponse200 = {
  data: UserReadDto
  status: 200
}
    
export type userControllerMeResponseSuccess = (userControllerMeResponse200) & {
  headers: Headers;
};
;

export type userControllerMeResponse = (userControllerMeResponseSuccess)

export const getUserControllerMeUrl = () => {


  

  return `/api/v1/users/me`
}

export const userControllerMe = async ( options?: RequestInit): Promise<userControllerMeResponse> => {
  
  return fetchMutator<userControllerMeResponse>(getUserControllerMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update profile of user
 */
export type userControllerUpdateProfileResponse200 = {
  data: UserReadDto
  status: 200
}
    
export type userControllerUpdateProfileResponseSuccess = (userControllerUpdateProfileResponse200) & {
  headers: Headers;
};
;

export type userControllerUpdateProfileResponse = (userControllerUpdateProfileResponseSuccess)

export const getUserControllerUpdateProfileUrl = () => {


  

  return `/api/v1/users/update-profile`
}

export const userControllerUpdateProfile = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<userControllerUpdateProfileResponse> => {
  
  return fetchMutator<userControllerUpdateProfileResponse>(getUserControllerUpdateProfileUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileDto,)
  }
);}



/**
 * @summary Update password of user
 */
export type userControllerUpdatePasswordResponse200 = {
  data: UserReadDto
  status: 200
}
    
export type userControllerUpdatePasswordResponseSuccess = (userControllerUpdatePasswordResponse200) & {
  headers: Headers;
};
;

export type userControllerUpdatePasswordResponse = (userControllerUpdatePasswordResponseSuccess)

export const getUserControllerUpdatePasswordUrl = () => {


  

  return `/api/v1/users/update-password`
}

export const userControllerUpdatePassword = async (updatePasswordDto: UpdatePasswordDto, options?: RequestInit): Promise<userControllerUpdatePasswordResponse> => {
  
  return fetchMutator<userControllerUpdatePasswordResponse>(getUserControllerUpdatePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePasswordDto,)
  }
);}



/**
 * @summary Get current admin
 */
export type adminV1AdminControllerGetMeResponse200 = {
  data: AdminReadV1DTO
  status: 200
}
    
export type adminV1AdminControllerGetMeResponseSuccess = (adminV1AdminControllerGetMeResponse200) & {
  headers: Headers;
};
;

export type adminV1AdminControllerGetMeResponse = (adminV1AdminControllerGetMeResponseSuccess)

export const getAdminV1AdminControllerGetMeUrl = () => {


  

  return `/api/v1/admin/admins/me`
}

export const adminV1AdminControllerGetMe = async ( options?: RequestInit): Promise<adminV1AdminControllerGetMeResponse> => {
  
  return fetchMutator<adminV1AdminControllerGetMeResponse>(getAdminV1AdminControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get admin list
 */
export type adminV1AdminControllerGetAdminListResponse200 = {
  data: AdminReadV1DTO[]
  status: 200
}
    
export type adminV1AdminControllerGetAdminListResponseSuccess = (adminV1AdminControllerGetAdminListResponse200) & {
  headers: Headers;
};
;

export type adminV1AdminControllerGetAdminListResponse = (adminV1AdminControllerGetAdminListResponseSuccess)

export const getAdminV1AdminControllerGetAdminListUrl = () => {


  

  return `/api/v1/admin/admins/list`
}

export const adminV1AdminControllerGetAdminList = async ( options?: RequestInit): Promise<adminV1AdminControllerGetAdminListResponse> => {
  
  return fetchMutator<adminV1AdminControllerGetAdminListResponse>(getAdminV1AdminControllerGetAdminListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create admin
 */
export type adminV1AdminControllerCreateAdminResponse200 = {
  data: AdminReadV1DTO
  status: 200
}
    
export type adminV1AdminControllerCreateAdminResponseSuccess = (adminV1AdminControllerCreateAdminResponse200) & {
  headers: Headers;
};
;

export type adminV1AdminControllerCreateAdminResponse = (adminV1AdminControllerCreateAdminResponseSuccess)

export const getAdminV1AdminControllerCreateAdminUrl = () => {


  

  return `/api/v1/admin/admins/create-admin`
}

export const adminV1AdminControllerCreateAdmin = async (adminCreateV1DTO: AdminCreateV1DTO, options?: RequestInit): Promise<adminV1AdminControllerCreateAdminResponse> => {
  
  return fetchMutator<adminV1AdminControllerCreateAdminResponse>(getAdminV1AdminControllerCreateAdminUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminCreateV1DTO,)
  }
);}



/**
 * @summary Update admin
 */
export type adminV1AdminControllerUpdateAdminResponse200 = {
  data: AdminReadV1DTO
  status: 200
}
    
export type adminV1AdminControllerUpdateAdminResponseSuccess = (adminV1AdminControllerUpdateAdminResponse200) & {
  headers: Headers;
};
;

export type adminV1AdminControllerUpdateAdminResponse = (adminV1AdminControllerUpdateAdminResponseSuccess)

export const getAdminV1AdminControllerUpdateAdminUrl = () => {


  

  return `/api/v1/admin/admins/update-admin`
}

export const adminV1AdminControllerUpdateAdmin = async (adminUpdateV1DTO: AdminUpdateV1DTO, options?: RequestInit): Promise<adminV1AdminControllerUpdateAdminResponse> => {
  
  return fetchMutator<adminV1AdminControllerUpdateAdminResponse>(getAdminV1AdminControllerUpdateAdminUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminUpdateV1DTO,)
  }
);}



/**
 * @summary Delete admin
 */
export type adminV1AdminControllerDeleteAdminResponse200 = {
  data: AdminReadV1DTO
  status: 200
}
    
export type adminV1AdminControllerDeleteAdminResponseSuccess = (adminV1AdminControllerDeleteAdminResponse200) & {
  headers: Headers;
};
;

export type adminV1AdminControllerDeleteAdminResponse = (adminV1AdminControllerDeleteAdminResponseSuccess)

export const getAdminV1AdminControllerDeleteAdminUrl = () => {


  

  return `/api/v1/admin/admins/delete-admin`
}

export const adminV1AdminControllerDeleteAdmin = async (adminDeleteV1DTO: AdminDeleteV1DTO, options?: RequestInit): Promise<adminV1AdminControllerDeleteAdminResponse> => {
  
  return fetchMutator<adminV1AdminControllerDeleteAdminResponse>(getAdminV1AdminControllerDeleteAdminUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminDeleteV1DTO,)
  }
);}



/**
 * @summary Create a new event
 */
export type eventAdminControllerCreateResponse201 = {
  data: EventResponseDto
  status: 201
}
    
export type eventAdminControllerCreateResponseSuccess = (eventAdminControllerCreateResponse201) & {
  headers: Headers;
};
;

export type eventAdminControllerCreateResponse = (eventAdminControllerCreateResponseSuccess)

export const getEventAdminControllerCreateUrl = () => {


  

  return `/api/v1/admin/events`
}

export const eventAdminControllerCreate = async (createEventDto: CreateEventDto, options?: RequestInit): Promise<eventAdminControllerCreateResponse> => {
  
  return fetchMutator<eventAdminControllerCreateResponse>(getEventAdminControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventDto,)
  }
);}



/**
 * @summary Get all events with pagination and filtering
 */
export type eventAdminControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type eventAdminControllerFindAllResponseSuccess = (eventAdminControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type eventAdminControllerFindAllResponse = (eventAdminControllerFindAllResponseSuccess)

export const getEventAdminControllerFindAllUrl = (params?: EventAdminControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/events?${stringifiedParams}` : `/api/v1/admin/events`
}

export const eventAdminControllerFindAll = async (params?: EventAdminControllerFindAllParams, options?: RequestInit): Promise<eventAdminControllerFindAllResponse> => {
  
  return fetchMutator<eventAdminControllerFindAllResponse>(getEventAdminControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get event by ID
 */
export type eventAdminControllerFindOneResponse200 = {
  data: EventResponseDto
  status: 200
}
    
export type eventAdminControllerFindOneResponseSuccess = (eventAdminControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type eventAdminControllerFindOneResponse = (eventAdminControllerFindOneResponseSuccess)

export const getEventAdminControllerFindOneUrl = (id: string,) => {


  

  return `/api/v1/admin/events/${id}`
}

export const eventAdminControllerFindOne = async (id: string, options?: RequestInit): Promise<eventAdminControllerFindOneResponse> => {
  
  return fetchMutator<eventAdminControllerFindOneResponse>(getEventAdminControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update an event
 */
export type eventAdminControllerUpdateResponse200 = {
  data: EventResponseDto
  status: 200
}
    
export type eventAdminControllerUpdateResponseSuccess = (eventAdminControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type eventAdminControllerUpdateResponse = (eventAdminControllerUpdateResponseSuccess)

export const getEventAdminControllerUpdateUrl = (id: string,) => {


  

  return `/api/v1/admin/events/${id}`
}

export const eventAdminControllerUpdate = async (id: string,
    updateEventDto: UpdateEventDto, options?: RequestInit): Promise<eventAdminControllerUpdateResponse> => {
  
  return fetchMutator<eventAdminControllerUpdateResponse>(getEventAdminControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventDto,)
  }
);}



/**
 * @summary Delete an event
 */
export type eventAdminControllerDeleteResponse204 = {
  data: void
  status: 204
}
    
export type eventAdminControllerDeleteResponseSuccess = (eventAdminControllerDeleteResponse204) & {
  headers: Headers;
};
;

export type eventAdminControllerDeleteResponse = (eventAdminControllerDeleteResponseSuccess)

export const getEventAdminControllerDeleteUrl = (id: string,) => {


  

  return `/api/v1/admin/events/${id}`
}

export const eventAdminControllerDelete = async (id: string, options?: RequestInit): Promise<eventAdminControllerDeleteResponse> => {
  
  return fetchMutator<eventAdminControllerDeleteResponse>(getEventAdminControllerDeleteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Send/log an event for the authenticated user
 */
export type eventUserControllerSendEventResponse201 = {
  data: void
  status: 201
}
    
export type eventUserControllerSendEventResponseSuccess = (eventUserControllerSendEventResponse201) & {
  headers: Headers;
};
;

export type eventUserControllerSendEventResponse = (eventUserControllerSendEventResponseSuccess)

export const getEventUserControllerSendEventUrl = () => {


  

  return `/api/v1/events/send`
}

export const eventUserControllerSendEvent = async (sendEventDto: SendEventDto, options?: RequestInit): Promise<eventUserControllerSendEventResponse> => {
  
  return fetchMutator<eventUserControllerSendEventResponse>(getEventUserControllerSendEventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendEventDto,)
  }
);}



/**
 * @summary Get count of events for the authenticated user
 */
export type eventUserControllerGetEventCountResponse200 = {
  data: EventCountResponseDto
  status: 200
}
    
export type eventUserControllerGetEventCountResponseSuccess = (eventUserControllerGetEventCountResponse200) & {
  headers: Headers;
};
;

export type eventUserControllerGetEventCountResponse = (eventUserControllerGetEventCountResponseSuccess)

export const getEventUserControllerGetEventCountUrl = (eventId: string,
    params?: EventUserControllerGetEventCountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/events/${eventId}/count?${stringifiedParams}` : `/api/v1/events/${eventId}/count`
}

export const eventUserControllerGetEventCount = async (eventId: string,
    params?: EventUserControllerGetEventCountParams, options?: RequestInit): Promise<eventUserControllerGetEventCountResponse> => {
  
  return fetchMutator<eventUserControllerGetEventCountResponse>(getEventUserControllerGetEventCountUrl(eventId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get event history for the authenticated user
 */
export type eventUserControllerGetEventHistoryResponse200 = {
  data: UserEventResponseDto[]
  status: 200
}
    
export type eventUserControllerGetEventHistoryResponseSuccess = (eventUserControllerGetEventHistoryResponse200) & {
  headers: Headers;
};
;

export type eventUserControllerGetEventHistoryResponse = (eventUserControllerGetEventHistoryResponseSuccess)

export const getEventUserControllerGetEventHistoryUrl = (eventId: string,
    params?: EventUserControllerGetEventHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/events/${eventId}/history?${stringifiedParams}` : `/api/v1/events/${eventId}/history`
}

export const eventUserControllerGetEventHistory = async (eventId: string,
    params?: EventUserControllerGetEventHistoryParams, options?: RequestInit): Promise<eventUserControllerGetEventHistoryResponse> => {
  
  return fetchMutator<eventUserControllerGetEventHistoryResponse>(getEventUserControllerGetEventHistoryUrl(eventId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get all events with pagination and filtering
 */
export type eventUserControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type eventUserControllerFindAllResponseSuccess = (eventUserControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type eventUserControllerFindAllResponse = (eventUserControllerFindAllResponseSuccess)

export const getEventUserControllerFindAllUrl = (params?: EventUserControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/events?${stringifiedParams}` : `/api/v1/events`
}

export const eventUserControllerFindAll = async (params?: EventUserControllerFindAllParams, options?: RequestInit): Promise<eventUserControllerFindAllResponse> => {
  
  return fetchMutator<eventUserControllerFindAllResponse>(getEventUserControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get event by ID
 */
export type eventUserControllerFindOneResponse200 = {
  data: EventResponseDto
  status: 200
}
    
export type eventUserControllerFindOneResponseSuccess = (eventUserControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type eventUserControllerFindOneResponse = (eventUserControllerFindOneResponseSuccess)

export const getEventUserControllerFindOneUrl = (id: string,) => {


  

  return `/api/v1/events/${id}`
}

export const eventUserControllerFindOne = async (id: string, options?: RequestInit): Promise<eventUserControllerFindOneResponse> => {
  
  return fetchMutator<eventUserControllerFindOneResponse>(getEventUserControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Health check
 */
export type healthControllerCheckResponse200 = {
  data: HealthControllerCheck200
  status: 200
}

export type healthControllerCheckResponse503 = {
  data: HealthControllerCheck503
  status: 503
}
    
export type healthControllerCheckResponseSuccess = (healthControllerCheckResponse200) & {
  headers: Headers;
};
export type healthControllerCheckResponseError = (healthControllerCheckResponse503) & {
  headers: Headers;
};

export type healthControllerCheckResponse = (healthControllerCheckResponseSuccess | healthControllerCheckResponseError)

export const getHealthControllerCheckUrl = () => {


  

  return `/api/health`
}

export const healthControllerCheck = async ( options?: RequestInit): Promise<healthControllerCheckResponse> => {
  
  return fetchMutator<healthControllerCheckResponse>(getHealthControllerCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get all leaderboards
 */
export type leaderboardControllerGetLeaderboardsResponse200 = {
  data: Leaderboard[]
  status: 200
}
    
export type leaderboardControllerGetLeaderboardsResponseSuccess = (leaderboardControllerGetLeaderboardsResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetLeaderboardsResponse = (leaderboardControllerGetLeaderboardsResponseSuccess)

export const getLeaderboardControllerGetLeaderboardsUrl = () => {


  

  return `/api/v1/games/leaderboards`
}

export const leaderboardControllerGetLeaderboards = async ( options?: RequestInit): Promise<leaderboardControllerGetLeaderboardsResponse> => {
  
  return fetchMutator<leaderboardControllerGetLeaderboardsResponse>(getLeaderboardControllerGetLeaderboardsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get all active leaderboards
 */
export type leaderboardControllerGetActiveLeaderboardsResponse200 = {
  data: Leaderboard[]
  status: 200
}
    
export type leaderboardControllerGetActiveLeaderboardsResponseSuccess = (leaderboardControllerGetActiveLeaderboardsResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetActiveLeaderboardsResponse = (leaderboardControllerGetActiveLeaderboardsResponseSuccess)

export const getLeaderboardControllerGetActiveLeaderboardsUrl = () => {


  

  return `/api/v1/games/leaderboards/active`
}

export const leaderboardControllerGetActiveLeaderboards = async ( options?: RequestInit): Promise<leaderboardControllerGetActiveLeaderboardsResponse> => {
  
  return fetchMutator<leaderboardControllerGetActiveLeaderboardsResponse>(getLeaderboardControllerGetActiveLeaderboardsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get a specific leaderboard by ID
 */
export type leaderboardControllerGetLeaderboardResponse200 = {
  data: Leaderboard
  status: 200
}
    
export type leaderboardControllerGetLeaderboardResponseSuccess = (leaderboardControllerGetLeaderboardResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetLeaderboardResponse = (leaderboardControllerGetLeaderboardResponseSuccess)

export const getLeaderboardControllerGetLeaderboardUrl = (id: string,) => {


  

  return `/api/v1/games/leaderboards/${id}`
}

export const leaderboardControllerGetLeaderboard = async (id: string, options?: RequestInit): Promise<leaderboardControllerGetLeaderboardResponse> => {
  
  return fetchMutator<leaderboardControllerGetLeaderboardResponse>(getLeaderboardControllerGetLeaderboardUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get top scores for a specific leaderboard
 */
export type leaderboardControllerGetTopScoresResponse200 = {
  data: UserLeaderboardDto[]
  status: 200
}
    
export type leaderboardControllerGetTopScoresResponseSuccess = (leaderboardControllerGetTopScoresResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetTopScoresResponse = (leaderboardControllerGetTopScoresResponseSuccess)

export const getLeaderboardControllerGetTopScoresUrl = (id: string,
    params?: LeaderboardControllerGetTopScoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/games/leaderboards/${id}/scores?${stringifiedParams}` : `/api/v1/games/leaderboards/${id}/scores`
}

export const leaderboardControllerGetTopScores = async (id: string,
    params?: LeaderboardControllerGetTopScoresParams, options?: RequestInit): Promise<leaderboardControllerGetTopScoresResponse> => {
  
  return fetchMutator<leaderboardControllerGetTopScoresResponse>(getLeaderboardControllerGetTopScoresUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get user rank in a specific leaderboard
 */
export type leaderboardControllerGetUserRankResponse200 = {
  data: UserLeaderboardDto
  status: 200
}
    
export type leaderboardControllerGetUserRankResponseSuccess = (leaderboardControllerGetUserRankResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetUserRankResponse = (leaderboardControllerGetUserRankResponseSuccess)

export const getLeaderboardControllerGetUserRankUrl = (id: string,) => {


  

  return `/api/v1/games/leaderboards/${id}/users/rank`
}

export const leaderboardControllerGetUserRank = async (id: string, options?: RequestInit): Promise<leaderboardControllerGetUserRankResponse> => {
  
  return fetchMutator<leaderboardControllerGetUserRankResponse>(getLeaderboardControllerGetUserRankUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get user neighbors in a specific leaderboard
 */
export type leaderboardControllerGetUserNeighborsResponse200 = {
  data: UserLeaderboardWithNeighborsDto
  status: 200
}
    
export type leaderboardControllerGetUserNeighborsResponseSuccess = (leaderboardControllerGetUserNeighborsResponse200) & {
  headers: Headers;
};
;

export type leaderboardControllerGetUserNeighborsResponse = (leaderboardControllerGetUserNeighborsResponseSuccess)

export const getLeaderboardControllerGetUserNeighborsUrl = (id: string,) => {


  

  return `/api/v1/games/leaderboards/${id}/users/neighbors`
}

export const leaderboardControllerGetUserNeighbors = async (id: string, options?: RequestInit): Promise<leaderboardControllerGetUserNeighborsResponse> => {
  
  return fetchMutator<leaderboardControllerGetUserNeighborsResponse>(getLeaderboardControllerGetUserNeighborsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get leaderboards list with pagination
 */
export type leaderboardAdminV1ControllerGetLeaderboardsResponse200 = {
  data: void
  status: 200
}
    
export type leaderboardAdminV1ControllerGetLeaderboardsResponseSuccess = (leaderboardAdminV1ControllerGetLeaderboardsResponse200) & {
  headers: Headers;
};
;

export type leaderboardAdminV1ControllerGetLeaderboardsResponse = (leaderboardAdminV1ControllerGetLeaderboardsResponseSuccess)

export const getLeaderboardAdminV1ControllerGetLeaderboardsUrl = () => {


  

  return `/api/v1/games/leaderboards/admin/list`
}

export const leaderboardAdminV1ControllerGetLeaderboards = async ( options?: RequestInit): Promise<leaderboardAdminV1ControllerGetLeaderboardsResponse> => {
  
  return fetchMutator<leaderboardAdminV1ControllerGetLeaderboardsResponse>(getLeaderboardAdminV1ControllerGetLeaderboardsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create new leaderboard
 */
export type leaderboardAdminV1ControllerCreateLeaderboardResponse200 = {
  data: void
  status: 200
}
    
export type leaderboardAdminV1ControllerCreateLeaderboardResponseSuccess = (leaderboardAdminV1ControllerCreateLeaderboardResponse200) & {
  headers: Headers;
};
;

export type leaderboardAdminV1ControllerCreateLeaderboardResponse = (leaderboardAdminV1ControllerCreateLeaderboardResponseSuccess)

export const getLeaderboardAdminV1ControllerCreateLeaderboardUrl = () => {


  

  return `/api/v1/games/leaderboards/admin/create`
}

export const leaderboardAdminV1ControllerCreateLeaderboard = async (createLeaderboardDto: CreateLeaderboardDto, options?: RequestInit): Promise<leaderboardAdminV1ControllerCreateLeaderboardResponse> => {
  
  return fetchMutator<leaderboardAdminV1ControllerCreateLeaderboardResponse>(getLeaderboardAdminV1ControllerCreateLeaderboardUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLeaderboardDto,)
  }
);}



/**
 * @summary Update leaderboard
 */
export type leaderboardAdminV1ControllerUpdateLeaderboardResponse200 = {
  data: void
  status: 200
}
    
export type leaderboardAdminV1ControllerUpdateLeaderboardResponseSuccess = (leaderboardAdminV1ControllerUpdateLeaderboardResponse200) & {
  headers: Headers;
};
;

export type leaderboardAdminV1ControllerUpdateLeaderboardResponse = (leaderboardAdminV1ControllerUpdateLeaderboardResponseSuccess)

export const getLeaderboardAdminV1ControllerUpdateLeaderboardUrl = (id: string,) => {


  

  return `/api/v1/games/leaderboards/admin/${id}/set-active`
}

export const leaderboardAdminV1ControllerUpdateLeaderboard = async (id: string,
    updateLeaderboardDto: UpdateLeaderboardDto, options?: RequestInit): Promise<leaderboardAdminV1ControllerUpdateLeaderboardResponse> => {
  
  return fetchMutator<leaderboardAdminV1ControllerUpdateLeaderboardResponse>(getLeaderboardAdminV1ControllerUpdateLeaderboardUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLeaderboardDto,)
  }
);}



/**
 * @summary Delete leaderboard
 */
export type leaderboardAdminV1ControllerDeleteLeaderboardResponse200 = {
  data: void
  status: 200
}
    
export type leaderboardAdminV1ControllerDeleteLeaderboardResponseSuccess = (leaderboardAdminV1ControllerDeleteLeaderboardResponse200) & {
  headers: Headers;
};
;

export type leaderboardAdminV1ControllerDeleteLeaderboardResponse = (leaderboardAdminV1ControllerDeleteLeaderboardResponseSuccess)

export const getLeaderboardAdminV1ControllerDeleteLeaderboardUrl = (id: string,) => {


  

  return `/api/v1/games/leaderboards/admin/${id}/delete`
}

export const leaderboardAdminV1ControllerDeleteLeaderboard = async (id: string, options?: RequestInit): Promise<leaderboardAdminV1ControllerDeleteLeaderboardResponse> => {
  
  return fetchMutator<leaderboardAdminV1ControllerDeleteLeaderboardResponse>(getLeaderboardAdminV1ControllerDeleteLeaderboardUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
